# -*- coding: utf-8 -*-
"""minimax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NAslclp-zuBDebAXwfmUxvah_dAq0ybU
"""

import math

# --- Cấu hình trò chơi ---
HUMAN = 'X'
AI = 'O'
EMPTY = ' '

def print_board(board):
    """In bảng cờ ra màn hình console"""
    print("-" * 13)
    for row in board:
        print(f"| {row[0]} | {row[1]} | {row[2]} |")
        print("-" * 13)

def check_winner(board):
    """
    Kiểm tra trạng thái game.
    Trả về: 'X' nếu Human thắng, 'O' nếu AI thắng, 'Draw' nếu hòa, None nếu chưa xong.
    """
    # Kiểm tra hàng ngang và dọc
    for i in range(3):
        if board[i][0] == board[i][1] == board[i][2] and board[i][0] != EMPTY:
            return board[i][0]
        if board[0][i] == board[1][i] == board[2][i] and board[0][i] != EMPTY:
            return board[0][i]

    # Kiểm tra đường chéo
    if board[0][0] == board[1][1] == board[2][2] and board[0][0] != EMPTY:
        return board[0][0]
    if board[0][2] == board[1][1] == board[2][0] and board[0][2] != EMPTY:
        return board[0][2]

    # Kiểm tra hòa (không còn ô trống)
    is_full = True
    for row in board:
        if EMPTY in row:
            is_full = False
            break
    if is_full:
        return 'Draw'

    return None

def minimax(board, depth, is_maximizing):
    """
    Thuật toán Minimax cốt lõi.
    """
    result = check_winner(board)
    if result == AI:
        return 10 - depth  # Ưu tiên thắng sớm
    elif result == HUMAN:
        return depth - 10  # Ưu tiên thua muộn (nếu bắt buộc thua)
    elif result == 'Draw':
        return 0

    if is_maximizing:
        best_score = -math.inf
        for i in range(3):
            for j in range(3):
                if board[i][j] == EMPTY:
                    board[i][j] = AI
                    score = minimax(board, depth + 1, False)
                    board[i][j] = EMPTY # Backtrack (hoàn tác)
                    best_score = max(score, best_score)
        return best_score
    else:
        best_score = math.inf
        for i in range(3):
            for j in range(3):
                if board[i][j] == EMPTY:
                    board[i][j] = HUMAN
                    score = minimax(board, depth + 1, True)
                    board[i][j] = EMPTY # Backtrack
                    best_score = min(score, best_score)
        return best_score

def get_best_move(board):
    """Tìm nước đi tốt nhất cho AI"""
    best_score = -math.inf
    move = (-1, -1)
    for i in range(3):
        for j in range(3):
            if board[i][j] == EMPTY:
                board[i][j] = AI
                score = minimax(board, 0, False)
                board[i][j] = EMPTY
                if score > best_score:
                    best_score = score
                    move = (i, j)
    return move

def play_game():
    """Hàm chính để chạy trò chơi"""
    board = [[EMPTY for _ in range(3)] for _ in range(3)]
    print("Tic-Tac-Toe: Bạn là X, AI là O")
    print_board(board)

    while True:
        # --- Lượt người chơi ---
        while True:
            try:
                row = int(input("Nhập hàng (0, 1, 2): "))
                col = int(input("Nhập cột (0, 1, 2): "))
                if 0 <= row <= 2 and 0 <= col <= 2 and board[row][col] == EMPTY:
                    board[row][col] = HUMAN
                    break
                else:
                    print("Ô không hợp lệ hoặc đã có người đánh. Thử lại!")
            except ValueError:
                print("Vui lòng nhập số nguyên!")

        print_board(board)

        # Kiểm tra kết thúc sau lượt người
        result = check_winner(board)
        if result:
            if result == 'Draw': print("Hòa!")
            else: print(f"Người chơi ({result}) thắng!")
            break

        # --- Lượt AI ---
        print("AI đang suy nghĩ...")
        ai_move = get_best_move(board)
        board[ai_move[0]][ai_move[1]] = AI
        print(f"AI đã đánh vào ô: {ai_move}")
        print_board(board)

        # Kiểm tra kết thúc sau lượt AI
        result = check_winner(board)
        if result:
            if result == 'Draw': print("Hòa!")
            else: print(f"AI ({result}) thắng!")
            break

# Chạy game
if __name__ == "__main__":
    play_game()