# -*- coding: utf-8 -*-
"""Buoi1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQZgu_dsyBz07Lvmj6Bo_CJ9RikYuGaO
"""

name = input("Your name is: ")
age = input("Age: ")
print(f"\nMy name is {name}")
print("Age = " + age)

def taxi():
  passengers = (int)(input("Nhap vao so nguoi: "))
  distance = (float)(input("Nhap vao so km: "))
  total = passengers * 2 + distance * 1.5
  print("\nTotal: ", total)
taxi()

string = input("string enter: ")
print(string[::2])

sum = 0
n = 11
for i in range(n):
  if i % 3 == 0 or i % 5 == 0:
    sum += i
print(f"Tong cac so tu 0 den {n} ma la boi 3 hoac 5 la: {sum}")

a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]
min = len(b) if len(a) > len(b) else len(a)
c = a if len(a) > len(b) else b
for i in range(min):
  c[i] = a[i] + b[i]
print(c)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = [x for x in fruits if "a" in x]
print(newlist)

import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

class Sach:
  dic_sach = {"masach": [],
              "tensach": [],
              "dongia": [],
              "soluong": [],
              }
  def __init__(self, n):
    for i in range(n):
      ma = input("Nhap ma sach: ")
      ten = input("Nhap ten sach: ")
      dg = float(input("Nhap don gia: "))
      sl = int(input("Nhap so luong: "))
      self.dic_sach['masach'].append(ma)
      self.dic_sach['tensach'].append(ten)
      self.dic_sach['dongia'].append(dg)
      self.dic_sach['soluong'].append(sl)
Sach(3)
print(Sach.dic_sach)
print("Tong so luong sach: " + str(sum(Sach.dic_sach["soluong"])))
for i in range(len(Sach.dic_sach["masach"])):
  if Sach.dic_sach["soluong"][i] > 10:
    print(Sach.dic_sach["tensach"][i])